---

- hosts: sq_server
  gather_facts: true

  roles:
  - role: pre-setup
    tags:
      - pre-setup

  - role: solarq-setup
    tags:
      - solarq

  - role: post-setup
    tags:
      - post-setup
