---
# tasks file for ansible-role-sonarqube/

- name: "Create {{ sonar_group }} system group"
  group:
    name: "{{ sonar_group }}"
    state: present

- name: "Create {{ sonar_user }} system user"
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    createhome: no
    shell: "/sbin/nologin"
    comment: "SonarQube System user"
    state: present

- name: "Create SonarQube directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ sonar_install_directory }}"
    - "{{ sonar_logs_dir }}"
    - "{{ sonar_data_dir }}"
    - "{{ sonar_temp_dir }}"

- name: "Install OpenJDK 11"
  apt:
    name:
      - openjdk-11-jdk
      - openjdk-11-jre
    state: latest
  register: install_jdk11

- name: "Ensure JAVA is installed"
  command: "java -version"
  register: prereq_java
  changed_when: false

- name: "Fail if JAVA is not available"
  fail:
    msg: "JAVA is not installed or configured"
  when: not prereq_java.rc == 0

- name: "Ensure required packages are installed"
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - procps
  when: ansible_os_family == 'Debian'

- name: Install additional packages
  apt:
    name:
      - unzip
    state: latest

- name: Set sysctl vm.max_map_count value
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '524288'
    sysctl_set: yes
    state: present
    reload: yes

- name: Set sysctl fs.file-max value
  ansible.posix.sysctl:
    name: fs.file-max
    value: '131072'
    sysctl_set: yes
    state: present
    reload: yes

- name: Add nofile & nproc limit for {{sonar_user}} user in /etc/security/limits.conf
  lineinfile:
    path: '/etc/security/limits.conf'
    regexp: '^{{sonar_user}}\s+'
    line: '{{item}}'
    state: present
    insertbefore: '^#\sEnd'
  with_items:
    - "{{sonar_user}}  -  nofile  131072"
    - "{{sonar_user}}  -  nproc  8192"
