---
# tasks file for ansible-role-sonarqube/

- name: "Create SonarQube system group"
  group:
    name: "{{ sonar_group }}"
    state: present

- name: "Create SonarQube system user"
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    createhome: no
    shell: "/sbin/nologin"
    comment: "SonarQube System user"
    state: present

- name: "Create SonarQube directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ sonar_install_directory }}"
    - "{{ sonar_logs_dir }}"
    - "{{ sonar_data_dir }}"
    - "{{ sonar_temp_dir }}"

- name: "Install OpenJDK 11"
  apt:
    name:
      - openjdk-11-jdk
      - openjdk-11-jre
    state: latest
  register: install_jdk11

- name: "Ensure JAVA is installed"
  command: "java -version"
  register: prereq_java
  changed_when: false

- name: "Fail if JAVA is not available"
  fail:
    msg: "JAVA is not installed or configured"
  when: not prereq_java.rc == 0

- name: "Ensure required packages are installed"
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - procps
  when: ansible_os_family == 'Debian' 

- name: Install additional packages
  apt:
    name:
      - unzip
    state: latest
- name: Set sysctl values
  - ansible.posix.sysctl:
    name: vm.max_map_count
    value: '524288'
    sysctl_set: yes
    state: present
    reload: yes