---

- name: Add mssql repo signing key
  apt_key: 
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Download mssql repo files
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/prod.list
    dest: /etc/apt/sources.list.d/msprod.list
    mode: '0644'

- name: "Install mssql tools"
  shell: |
      apt update -y
      ACCEPT_EULA=Y apt-get install mssql-tools  msodbcsql17 -y